name:                xlc
version:             0.1.0.0
github:              "kevorr/xlc"
license:             BSD-3-Clause
author:              "Kevin Orr"
copyright:           "2024 Kevin Orr"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/kevorr/xlc#readme>

dependencies:
  - base >= 4.7 && < 5

language: GHC2021

default-extensions:
  - BlockArguments
  - LambdaCase
  - OverloadedStrings

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - directory
    - filepath >=1.4.100 && <1.5.3
    - process
    - string-conversions
    - stringsearch
    - text >=2.0 && <2.2
    - time
    - zip-archive >=0.4 && <0.5
  exposed-modules:
    - XLam
    - XLam.Lang
    - XLam.Library

executables:
  xlc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - xlc

tests:
  xlc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xlc
